version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      TYPEORM_TYPE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./config/dev.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      TYPEORM_HOST: postgres
    ports:
      - "4000:4000"
      - "7777:7777"
    volumes:
      - .:/app

volumes:
  postgres_data: